http_api_addr = ":9090"
dns_api_addr = ":1053"

# 是否打开LocalDNS模式
localdns = true

# 解析规则缓存刷新间隔秒数
cache_ttl = 10

mysql = "huya_yunwei:Uy83Pmx#m.P@tcp(221.228.202.24:6301)/gslb?charset=utf8"

geofmt="ipip"
geodb="./ipip.txtx"

log_dir="./logs/"
